//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u21652296ToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int TaskID { get; set; }
        public Nullable<int> ListItemID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual ListItem ListItem { get; set; }
        public virtual ListItemPriority ListItemPriority { get; set; }
    }
}
